In [2]:
import pandas as pd
import numpy as np
mixes_1 = pd.read_excel('mixes_2017-2021_b1.xlsx',
     engine='openpyxl')

In [3]:
target = mixes_1[['Дата', 'Качество кокса,% (Показатели прочности,% — M25)', 
                  'Качество кокса,% (Показатели прочности,% — M10)', 
                  'Качество кокса,% (Показатели прочности,% — CSR)']]
target.columns = ["ДатаПробыКокса", "M25", "M10", "CSR"]
target["ДатаШихтовки"] = target["ДатаПробыКокса"] - pd.Timedelta(4, "d")
target

/home/user9/.local/lib/python3.6/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

     ДатаПробыКокса   M25  M10   CSR ДатаШихтовки
0        2017-01-01  88.3  7.8   NaN   2016-12-28
1        2017-01-02  88.5  7.4  60.9   2016-12-29
2        2017-01-03  88.3  7.7   NaN   2016-12-30
3        2017-01-04  88.2  7.7   NaN   2016-12-31
4        2017-01-05  88.7  7.7   NaN   2017-01-01
...             ...   ...  ...   ...          ...
1728     2021-10-15  87.3  7.8  60.5   2021-10-11
1729     2021-10-16  87.1  7.8   NaN   2021-10-12
1730     2021-10-17  87.4  8.0   NaN   2021-10-13
1731     2021-10-18  87.2  7.6   NaN   2021-10-14
1732     2021-10-19  87.2  7.5   NaN   2021-10-15

[1733 rows x 5 columns]

In [4]:
features = mixes_1[["Дата", "Состав шихты,%(спек.)", "Состав шихты,%(в т.ч. Марка Ж)", "Состав шихты,%(в т.ч. кокс.)",
                    "Оборот печей, час", "Качество шихты (помол,%)", "Качество шихты (пыль,%)", 
                    "Качество шихты (Технический анализ, % — влага)", "Качество шихты (Технический анализ, % — зола)",
                    "Качество шихты (Технический анализ, % — летуч.)", "Качество шихты (Мд. Серы,%)",
                    "Качество шихты (пласт. слой мм)", 'R0', 'σ', 'Vt', 'I', 'Io', 'SI', 'КТЦ эксп.', 'MF', 
                    'MF_spec',  'MF_otosh', 'CSR_carb']]


features.columns = ["ДатаШихтовки", "% спек", "% марка Ж", "% кокс.", "Оборот печей, ч", "Помол, %",
                    "Пыль, %", "Влага, %", "Зола, %", "Летуч., %", "Мд. Серы, %", "Пласт. слой, мм", 
                    'R0', 'σ', 'Vt', 'I', 'Io', 'SI', 'КТЦ эксп.', 'MF', 
                    'MF_spec',  'MF_otosh', 'CSR_carb']

features

,ДатаШихтовки,% спек,% марка Ж,% кокс.,"Оборот печей, ч","Помол, %","Пыль, %","Влага, %","Зола, %","Летуч., %",...,σ,Vt,I,Io,SI,КТЦ эксп.,MF,MF_spec,MF_otosh,CSR_carb
0,2017-01-01,50.0,29.8,28,19.50,77.9,39.9,8.4,8.8,26.1,...,0.059921,62.14549,21.998627,0.20525,5.810,0.7408,14116.40,14095.0,21.40,41.660
1,2017-01-02,50.0,29.8,28,19.50,77.0,40.1,8.5,8.5,25.2,...,0.059921,62.14549,21.998627,0.20525,5.810,0.7408,14116.40,14095.0,21.40,41.660
2,2017-01-03,50.0,29.8,28,19.50,76.6,39.1,9.2,8.1,25.7,...,0.059921,62.14549,21.998627,0.20525,5.810,0.7408,14116.40,14095.0,21.40,41.660
3,2017-01-04,50.0,29.8,28,19.50,76.1,38.7,9.2,8.2,25.7,...,0.059921,62.14549,21.998627,0.20525,5.810,0.7408,14116.40,14095.0,21.40,41.660
4,2017-01-05,50.0,29.8,28,19.50,77.6,39.0,8.2,8.6,25.1,...,0.059921,62.14549,21.998627,0.20525,5.810,0.7408,14116.40,14095.0,21.40,41.660
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1728,2021-10-15,46.0,35.4,50,18.75,76.4,39.6,9.6,7.9,26.5,...,0.048420,44.07000,21.080000,0.15976,3.585,0.6208,5364.75,5250.0,114.75,44.298
1729,2021-10-16,46.0,29.7,50,18.25,76.4,39.2,9.8,7.9,26.5,...,0.058920,54.27000,22.730000,0.19810,4.650,0.7303,8980.20,8850.0,130.20,49.878
1730,2021-10-17,46.0,29.7,50,18.25,76.0,38.7,9.8,8.4,26.0,...,0.058920,54.27000,22.730000,0.19810,4.650,0.7303,8980.20,8850.0,130.20,49.878
1731,2021-10-18,46.0,29.7,50,18.25,76.3,39.2,10.0,8.2,25.8,...,0.058920,54.27000,22.730000,0.19810,4.650,0.7303,8980.20,8850.0,130.20,49.878
1732,2021-10-19,46.0,29.7,50,18.25,76.6,39.4,9.9,8.0,26.0,...,0.058920,54.27000,22.730000,0.19810,4.650,0.7303,8980.20,8850.0,130.20,49.878

In [5]:
data_aligned_b1 = pd.merge(target, features)
data_aligned_b1["Оборот печей отсеч, ч"] = np.where(data_aligned_b1['Оборот печей, ч'] >= 18, 18, data_aligned_b1['Оборот печей, ч'])
data_aligned_b1

,ДатаПробыКокса,M25,M10,CSR,ДатаШихтовки,% спек,% марка Ж,% кокс.,"Оборот печей, ч","Помол, %",...,Vt,I,Io,SI,КТЦ эксп.,MF,MF_spec,MF_otosh,CSR_carb,"Оборот печей отсеч, ч"
0,2017-01-05,88.7,7.7,NaN,2017-01-01,50.0,29.8,28,19.50,77.9,...,62.14549,21.998627,0.20525,5.810,0.7408,14116.40,14095.0,21.40,41.660,18.0
1,2017-01-06,88.7,7.5,NaN,2017-01-02,50.0,29.8,28,19.50,77.0,...,62.14549,21.998627,0.20525,5.810,0.7408,14116.40,14095.0,21.40,41.660,18.0
2,2017-01-07,88.6,7.6,NaN,2017-01-03,50.0,29.8,28,19.50,76.6,...,62.14549,21.998627,0.20525,5.810,0.7408,14116.40,14095.0,21.40,41.660,18.0
3,2017-01-08,88.1,7.6,NaN,2017-01-04,50.0,29.8,28,19.50,76.1,...,62.14549,21.998627,0.20525,5.810,0.7408,14116.40,14095.0,21.40,41.660,18.0
4,2017-01-09,88.5,7.8,60.7,2017-01-05,50.0,29.8,28,19.50,77.6,...,62.14549,21.998627,0.20525,5.810,0.7408,14116.40,14095.0,21.40,41.660,18.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1707,2021-10-15,87.3,7.8,60.5,2021-10-11,46.0,35.4,50,18.00,74.8,...,41.39000,20.040000,0.14960,3.785,0.5964,5402.95,5250.0,152.95,40.782,18.0
1708,2021-10-16,87.1,7.8,NaN,2021-10-12,46.0,35.4,50,20.25,74.1,...,41.39000,20.040000,0.14960,3.785,0.5964,5402.95,5250.0,152.95,40.782,18.0
1709,2021-10-17,87.4,8.0,NaN,2021-10-13,46.0,35.4,50,18.00,75.0,...,41.39000,20.040000,0.14960,3.785,0.5964,5402.95,5250.0,152.95,40.782,18.0
1710,2021-10-18,87.2,7.6,NaN,2021-10-14,46.0,35.4,50,20.75,75.4,...,44.07000,21.080000,0.15976,3.585,0.6208,5364.75,5250.0,114.75,44.298,18.0
1711,2021-10-19,87.2,7.5,NaN,2021-10-15,46.0,35.4,50,18.75,76.4,...,44.07000,21.080000,0.15976,3.585,0.6208,5364.75,5250.0,114.75,44.298,18.0